# Generated by Django 4.0.5 on 2022-06-29 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conversation', models.IntegerField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInitConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_identifier', models.ManyToManyField(related_name='user1_chat_identifier', to=settings.AUTH_USER_MODEL)),
                ('user2_identifier', models.ManyToManyField(related_name='user2_chat_identifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
