# Generated by Django 4.0.5 on 2022-06-29 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinitconversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='usersinitconversation',
            name='id_conversation',
            field=models.CharField(default=None, editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='idconversation',
            name='id_conversation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userinit_id', to='chat.usersinitconversation', to_field='id_conversation'),
        ),
        migrations.RemoveField(
            model_name='usersinitconversation',
            name='user1_identifier',
        ),
        migrations.AddField(
            model_name='usersinitconversation',
            name='user1_identifier',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1_chat_identifier', to=settings.AUTH_USER_MODEL, to_field='identifier'),
        ),
        migrations.RemoveField(
            model_name='usersinitconversation',
            name='user2_identifier',
        ),
        migrations.AddField(
            model_name='usersinitconversation',
            name='user2_identifier',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2_chat_identifier', to=settings.AUTH_USER_MODEL, to_field='identifier'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('id_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.idconversation', to_field='id_conversation')),
                ('user_identifier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_identifier', to=settings.AUTH_USER_MODEL, to_field='identifier')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
