# Generated by Django 4.0.5 on 2022-06-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('NoticeId', models.AutoField(primary_key=True, serialize=False)),
                ('NoticeTitle', models.CharField(max_length=50)),
                ('NoticeDescription', models.CharField(max_length=500)),
                ('NoticeDateAdd', models.DateField()),
            ],
        ),
    ]
