# Generated by Django 4.0.5 on 2022-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('NoticeId', models.AutoField(primary_key=True, serialize=False)),
                ('NoticeTitle', models.CharField(max_length=50)),
                ('NoticeDescription', models.CharField(max_length=500)),
                ('NoticeDateAdd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
