# Generated by Django 4.0.5 on 2022-06-19 13:21

from django.db import migrations, models
import lendu.models


class Migration(migrations.Migration):

    dependencies = [
        ('lendu', '0002_notices_delete_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=lendu.models.upload_to),
        ),
    ]
