# Generated by Django 4.0.5 on 2022-06-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendu', '0003_notices_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notices',
            old_name='image_url',
            new_name='NoticeImg',
        ),
    ]
