# Generated by Django 4.0.5 on 2022-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendu', '0005_notices_noticedateupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='NoticeCategory',
            field=models.CharField(blank=True, default='Brak', max_length=50),
        ),
    ]
