# Generated by Django 4.0.5 on 2022-06-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendu', '0007_alter_notices_noticecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='NoticeCategory',
        ),
    ]
