# Generated by Django 4.0.5 on 2022-06-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lendu', '0010_notices_noticecredit_notices_noticecredit_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='NoticeOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to=settings.AUTH_USER_MODEL),
        ),
    ]
